site_name: Selecting software modules
site_url: https://hpc2n.github.io/selecting-modules/
site_description: Material for the course Login and selecting software modules
site_dir: site.build
theme:
  name: readthedocs
  locale: en
  logo: images/logo-modules-course_v2.png
  include_sidebar: true
  font:
    code: Robot Mono
  features:
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  tabs: true
  language: en
extra_css:
  - css/extra.css
    #extra_javascript:
    #  - js/popper.min.js
    #  - js/tippy-bundle.umd.js
    #  - js/clipboard.js

nav:
  - Home: index.md
  - Introduction: intro.md
  - Preparations: prep.md
  - The module system: module-overview.md
  - Useful commands: commands.md
  - Load examples: loading.md
  - Compiler toolchains: toolchains.md
  - Program examples: programs.md
  - Summary: summary.md
plugins:
  - search
  - external-markdown
  - mkdocstrings
  - markdown-exec
  - open-in-new-tab

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - smarty
  - pymdownx.details
  - pymdownx.superfences
  - codehilite
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      separator: "__"
